# Home page elements
logo = "xpath://div[@id='main_header']//a[@class='hslogo logo-image']//img"
openLearnLogo = "xpath://div[@id='main_header']//div[@class='main-logo']//img"
tagLine = "xpath://div[@id='main_wrapper']//div[@class='tagline']//a[1]"
link_theOpenUniversity = "xpath://ul[@id='sbhsnavigation']//li[@class='first']//a[contains(text(),'The Open University')]"
link_studyWithTheOpenUniversity = "xpath://ul[@id='sbhsnavigation']//a[contains(text(),'Study with The Open University')]"
text_searchFor = "xpath://div[@id='main_header']//label[@class='main_search_label'][contains(text(),'Search for')]"
input_searchBox = "xpath://input[@id='main_search_text_header_sticky']"
button_search = "xpath://div[@id='main_header']//button[@class='search icon-search']"
link_Home = "xpath://div[@id='mainMenu-left']//a[contains(text(),'Home')]"
link_FreeCourses = "xpath://div[@id='mainMenu-left']//a[contains(text(),'Free courses')]"
link_Subjects = "xpath://div[@id='mainMenu-left']//a[contains(text(),'Subjects')]"
link_ForStudy = "xpath://div[@id='mainMenu-left']//a[contains(text(),'For Study')]"
link_ForLife = "xpath://div[@id='mainMenu-left']//a[contains(text(),'For Life')]"
link_Help = "xpath://div[@id='mainMenu-left']//a[contains(text(),'Help')]"
link_SignIn = "xpath://a[@class='openlearnng_signin_signout btn-sidebar btn-olive']"
mainImage = "xpath://div[@class='gradient-img']//img"
text_bannerHeading = "xpath://h1[@id='banner_search_label']"
text_bannerSubHeading = "xpath://p[@id='banner_search_sub_label']"
input_bannerSearchBox = "xpath://input[@id='banner_search_text']"
button_bannerSearch = "xpath://a[@class='search']"
button_scroll = "xpath://a[@id='scroll-content']"
