
Logo_Header = "xpath://body/div[@id='wrapper']/div[@id='content']/div[@id='divLogin']/div[@id='divLogo']/img[1]"
Text_Username_Password = "xpath://span[contains(text(),'( Username : Admin | Password : admin123 )')]"
Text_LOGIN_Panel = "xpath://div[@id='logInPanelHeading']"
Circle_HRMForAll = "xpath://*[name()='circle' and contains(@fill,'url(#g)')]"

Background_Header_Form = "xpath://*[name()='path' and contains(@fill,'url(#d)')]"
txt_UserName = "id:txtUsername"
Person_Icon = "xpath://*[name()='g' and contains(@fill,'gray')]"
txt_Password = "id:txtPassword"
Lock_Icon = "xpath://*[name()='path' and contains(@fill,'gray')]"
btn_login = "xpath://input[@id='btnLogin']"
Forgot_your_password = "xpath://a[contains(text(),'Forgot your password?')]"

span_username = "xpath:(//span[normalize-space()='Username'])[1]"
span_password = "xpath:(//span[normalize-space()='Password'])[1]"

Text_Footer = "xpath://body/div[@id='wrapper']/div[@id='content']/div[@id='footer']/div[1]"
OrangeHRM_Inc = "xpath://a[contains(text(),'OrangeHRM, Inc')]"
Link_Icon = "xpath://img[@alt='LinkedIn OrangeHRM group']"
Facebook_Icon = "xpath://img[@alt='OrangeHRM on Facebook']"
Twitter_Icon = "xpath://img[@alt='OrangeHRM on twitter']"
Youtube_Icon = "xpath://img[@alt='OrangeHRM on youtube']"
Div_Login = "//div[@id='divLogin']"
text_footer = "xpath://div[contains(text(),'OrangeHRM 4.10.1')]"
