
# SideBar
FullName = "xpath://h1[contains(text(),'Ananya Dash')]"
Epic_Image = "xpath://img[@id='empPic']"
PersonalDetail_Link = "xpath://a[contains(text(),'Personal Details')]"
ContactDetail_Link = "xpath://a[contains(text(),'Contact Details')]"
EmergencyContacts_Link = "xpath://a[contains(text(),'Emergency Contacts')]"
Dependents_Link = "xpath://a[contains(text(),'Dependents')]"
Immigration_Link = "xpath://a[contains(text(),'Immigration')]"
Job_Link = "xpath://a[contains(text(),'Job')]"
Salary_Link = "xpath://a[contains(text(),'Salary')]"
TaxExemptions_Link = "xpath://a[contains(text(),'Tax Exemptions')]"
ReportTo_Link = "xpath://a[contains(text(),'Report-to')]"
Qualifications_Link = "xpath://a[contains(text(),'Qualifications')]"
Memberships_Link = "xpath://a[contains(text(),'Memberships')]"

# Personal Details
txt_FullName = "xpath://label[contains(text(),'Full Name')]"
txt_FirstName = "xpath:(//div[@class='fieldDescription'])[1]"
txt_MiddleName = "xpath://div[contains(text(),'Middle Name')]"
txt_Lastname = "xpath:(//div[@class='fieldDescription'])[3]"

input_FirstName = "xpath://input[@id='personal_txtEmpFirstName']"
input_MiddleName = "xpath://input[@id='personal_txtEmpMiddleName']"
input_LastName = "xpath://input[@id='personal_txtEmpLastName']"

txt_EmployeeId = "xpath://label[contains(text(),'Employee Id')]"
input_EmployeeId = "xpath://input[@id='personal_txtEmployeeId']"
txt_OtherId = "xpath://label[contains(text(),'Other Id')]"
input_OtherId = "xpath://input[@id='personal_txtOtherID']"
txt_DriverLicenseNumber = "xpath://label[@for='personal_txtLicenNo']"
input_DriverLicenseNumber = "xpath://input[@id='personal_txtLicenNo']"
txt_LicenseExpiryDate = "xpath://label[contains(text(),'License Expiry Date')]"
datetimepicker_LicenseExpiryDate = "xpath://input[@id='personal_txtLicExpDate']"
img_Calender_License = "xpath://ol[2]//li[4]//img[1]"
txt_SSNNumber = "xpath://label[contains(text(),'SSN Number')]"
input_SSN_Number = "xpath://input[@id='personal_txtNICNo']"
txt_SSIN_Number = "xpath://label[contains(text(),'SIN Number')]"
input_SSIN_Number = "xpath://input[@id='personal_txtSINNo']"
txt_Gender = "xpath://label[normalize-space()='Gender']"
radiobutton_Male = "xpath://li[@class='radio']//li[1]"
radiobutton_Female = "xpath://li[@class='radio']//li[2]"
txt_MaritalStatus = "xpath://label[contains(text(),'Marital Status')]"
dropdown_MaritalStatus = "xpath://select[@id='personal_cmbMarital']"
txt_Nationality = "xpath://label[contains(text(),'Nationality')]"
dropdown_Nationality = "xpath://select[@id='personal_cmbNation']"
txt_DateOfBirth = "xpath://label[contains(text(),'Date of Birth')]"
input_DateOfBirth = "xpath://input[@id='personal_DOB']"
img_Calender = "xpath://ol[3]//li[4]//img[1]"
txt_NickName = "xpath://label[contains(text(),'Nick Name')]"
input_NickName = "xpath://input[@id='personal_txtEmpNickName']"
txt_Smoker = "xpath://label[contains(text(),'Smoker')]"
checkbox_Smoker = "xpath://input[@id='personal_chkSmokeFlag']"
txt_MilitaryService = "xpath://label[contains(text(),'Military Service')]"
input_MilitaryService = "xpath://input[@id='personal_txtMilitarySer']"
txt_RequiredField = "xpath://li[@class='required new']"
btn_Save = "xpath://input[@id='btnSave']"

message_required_FN = "xpath://li[@class='line nameContainer']//li[1]//span[1]"
message_required_LN = "xpath://li[3]//span[1]"
message_verify_datetime = "xpath://span[contains(text(),'Should be a valid date in yyyy-mm-dd format')]"

# Custom Fields
txt_CustomFields = "xpath://h1[normalize-space()='Custom Fields']"
txt_BloodType = "xpath://label[normalize-space()='Blood Type']"
dropdown_BloodType = "xpath://select[@name='custom1']"
btn_EditCustomFields = "xpath://input[@id='btnEditCustom']"

# Attachments
txt_Attachments = "xpath://h1[normalize-space()='Attachments']"
btn_AddAttachment = "xpath://input[@id='btnAddAttachment']"
txt_SelectFile = "xpath://label[@id='selectFileSpan']"
input_SelectFile = "xpath://input[@id='ufile']"
txt_Accept = "xpath://label[contains(text(),'Accepts up to 1MB')]"
txt_Comment = "xpath://label[contains(text(),'Comment')]"
input_Comment = "xpath://textarea[@id='txtAttDesc']"
txt_RequiredFile_Attachments = "xpath://li[@class='required']"
btn_SaveAttachments = "xpath://input[@id='btnSaveAttachment']"
btn_Cancel = "xpath://input[@id='cancelButton']"
message_required = "xpath://span[@for='ufile']"
btn_DeleteAttachments = "xpath://input[@id='btnDeleteAttachment']"

checkall_Column = "xpath://input[@id='attachmentsCheckAll']"
fileName_Column = "xpath://th[contains(text(),'File Name')]"
description_Column = "xpath://th[contains(text(),'Description')]"
size_Column = "xpath://th[contains(text(),'Size')]"
type_Column = "xpath://th[contains(text(),'Type')]"
dateAdded_Column = "xpath://th[contains(text(),'Date Added')]"
addedBy_Column = "xpath://th[contains(text(),'Added By')]"
actionEdit_Column = "xpath://thead/tr[1]/th[8]"
data_FileName = "xpath://a[contains(text(),'Test_0.01MB.docx')]"

# Edit Attachments
btnEdit_AttachmentItem = "xpath://a[contains(text(),'Edit')]"
txt_CurrentFile = "xpath://label[contains(text(),'Current File')]"
input_CurrentFile = "xpath://span[@id='currentFileSpan']"
txt_ReplaceWith = "xpath://label[@id='selectFileSpan']"
txt_Comment = "xpath://label[contains(text(),'Comment')]"
btn_CommentOnly = "xpath://input[@id='btnCommentOnly']"

# Message success
txt_success = "xpath://div[@class='mb-heading ac_over']"
txt_SuccessfullySaved = "xpath://div[@id='successBodyEdit']"
txt_SuccessfullyShared = "xpath://div[@id='successBodyShare']"
txt_SuccessfullyDeleted = "xpath://div[@id='successBodyDelete']"

table = "xpath://table[@class='ui-datepicker-calendar']"
click_Download = "xpath://div[@id='tiptip_content']"

ele_Month = "xpath://select[@class='ui-datepicker-month']"
ele_Year = "xpath://select[@class='ui-datepicker-year']"
back_month = "xpath://span[contains(text(),'Prev')]"
next_month = "xpath:////span[contains(text(),'Next')]"
select_datetime = "xapth://div[@id='ui-datepicker-div']"

# PIM
link_PIM = "id:menu_pim_viewPimModule"
input_Id = "id:empsearch_id"
btn_search = "id:searchBtn"
id_value = "xpath://a[contains(text(),'0256')]"
check_id = "id:ohrmList_chkSelectRecord_43"
